spark.master                                    local[*]
spark.driver.memory                             4g
spark.sql.shuffle.partitions                    8
spark.hadoop.fs.defaultFS                       hdfs://namenode:9000
spark.hadoop.dfs.client.use.datanode.hostname   true
spark.hadoop.dfs.datanode.use.datanode.hostname false
spark.hadoop.dfs.client.read.shortcircuit       false
